### ISSUE TITLE
[BUG] mppcava shared library issue on Linux Mint

### ISSUE THREAD

**Issue by doctorfree** [doctorfree/mppcava#1]
Moved from `mpcplus` repo. Issue opened by @JOJ0
---------------
Hi again, on Linux Mint it seems mppcava faces a similar issue as mpcplus did recently. I open the issue here since your fork of cava repo does not have the issues feature enabled - I think that's a default setting on forks on github. It can still be enabled in the repo's setting if desired btw.

```
$ mppcava
mppcava: error while loading shared libraries: libportaudio.so.2: cannot open shared object file: No such file or directory
```

```
$ apt show mppcava
Package: mppcava
Version: 1.0.1-1
Status: install ok installed
Priority: optional
Section: sound
Maintainer: Ronald Record <ronaldrecord@gmail.com>
Installed-Size: 5.120 kB
Depends: libncursesw6 (>= 6), libfftw3-dev, libiniparser-dev, libsdl2-dev, libasound2, libpulse-dev
Homepage: https://github.com/doctorfree/mppcava
Build-Depends: debhelper (>= 11)
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Bar audio spectrum visualizer

$ lsb_release -a
No LSB modules are available.
Distributor ID: Linuxmint
Description:    Linux Mint 21.1
Release:        21.1
Codename:       vera
```

**Comment by doctorfree** [comment]
This looks like a missing dependency on `libportaudio`

This version of `mppcava` was built with Portaudio support enabled but the dependency on libportaudio was not added to the packaging.

**Comment by doctorfree** [comment]
A dependency on `portaudio` was added to the `mppcava` packaging for all platforms and a new release created. This should address this issue. However, it is still true that any previous version of `mppcava` must be removed and either install this new release or install `MusicPlayerPlus` and run `mppinit`. 

The new release of `mppcava` can be found at https://github.com/doctorfree/mppcava/releases/tag/v1.0.1r1

I am leaving this open while I test on all platforms.

**Comment by JOJ0** [comment]
I can confirm that the new version works on my Linux Mint box. Thanks a lot for fixing!

**Comment by doctorfree** [comment]
All tests on all platforms succeed. Closing.
